// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title VeriPhysLite
 * @author Narukihto / VeriPhys Team
 * @notice Optimized for high-frequency data anchoring from the VeriPhys Rust engine.
 * @dev High-throughput ledger with minimal gas overhead and enhanced event indexing.
 */
contract IntegrityLedger {
    
    // Mapping of SHA3-256 fingerprints to their respective block timestamps
    // Private visibility with a public getter follows security best practices
    mapping(bytes32 => uint256) private _ledger;

    // Custom errors: significantly cheaper than revert strings for gas efficiency
    error HashAlreadyAnchored(bytes32 hash, uint256 timestamp);
    error InvalidHash();

    // Indexed parameters allow the Rust backend to filter logs efficiently
    event Anchored(bytes32 indexed hash, uint256 indexed timestamp);

    /**
     * @notice Anchors a unique data fingerprint onto the blockchain.
     * @param _hash The cryptographic hash generated by the VeriPhys engine.
     */
    function anchorContent(bytes32 _hash) external {
        // 1. Integrity Check: Ensure the hash is not null
        if (_hash == bytes32(0)) revert InvalidHash();
        
        // 2. Conflict Check: Verify if this hash was already recorded
        uint256 existingTime = _ledger[_hash];
        if (existingTime != 0) revert HashAlreadyAnchored(_hash, existingTime);

        // 3. State Mutation: Store the current block timestamp
        _ledger[_hash] = block.timestamp;

        // 4. Log Emission: Facilitate off-chain synchronization
        emit Anchored(_hash, block.timestamp);
    }

    /**
     * @notice Retrieves the timestamp when a specific hash was anchored.
     * @param _hash The fingerprint to verify.
     * @return timestamp The unix timestamp (returns 0 if the hash does not exist).
     */
    function verify(bytes32 _hash) external view returns (uint256) {
        return _ledger[_hash];
    }
    
    /**
     * @notice Helper function for quick boolean verification.
     * @param _hash The fingerprint to check.
     * @return exists True if the hash is already on the ledger.
     */
    function exists(bytes32 _hash) external view returns (bool) {
        return _ledger[_hash] != 0;
    }
}
