events { worker_connections 1024; }

http {
    upstream veriphys_backend {
        server veriphys-engine:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Serve static frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Proxy API requests to the Rust Engine
        location /api/ {
            proxy_pass http://veriphys_backend/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Crucial for high-throughput blockchain data
            proxy_buffering off; 
        }
    }
}
