// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title VeriPhysIntegrityLedger
 * @dev High-performance anchoring for digital asset fingerprints.
 */
contract IntegrityLedger {
    
    // Structure to store asset details on-chain
    struct Anchor {
        uint256 timestamp;
        address author;
        bool exists;
    }

    // Mapping from SHA3-256 hash to Anchor data
    mapping(bytes32 => Anchor) private ledger;

    // Event emitted when a new asset is secured
    event ContentAnchored(bytes32 indexed contentHash, address indexed author, uint256 timestamp);

    /**
     * @dev Anchors a unique SHA3-256 fingerprint to the blockchain.
     * @param _contentHash The 32-byte hash generated by the VeriPhys Rust Engine.
     */
    function anchorContent(bytes32 _contentHash) external {
        // Prevent re-anchoring to save gas and maintain integrity
        require(!ledger[_contentHash].exists, "VeriPhys: Content already anchored");

        ledger[_contentHash] = Anchor({
            timestamp: block.timestamp,
            author: msg.sender,
            exists: true
        });

        emit ContentAnchored(_contentHash, msg.sender, block.timestamp);
    }

    /**
     * @dev Verifies if a content hash exists in the global ledger.
     * @param _contentHash The SHA3-256 hash to check.
     * @return exists Boolean status of authenticity.
     * @return timestamp The exact time the asset was first secured.
     * @return author The address that originally anchored the asset.
     */
    function verifyContent(bytes32 _contentHash) external view returns (
        bool exists, 
        uint256 timestamp, 
        address author
    ) {
        Anchor memory record = ledger[_contentHash];
        return (record.exists, record.timestamp, record.author);
    }
}
