// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title VeriPhys Protocol - Secure Integrity Ledger
 * @author Your Name / VeriPhys Team
 * @notice Provides immutable proof of existence for digital assets using SHA3-256 fingerprints.
 * @dev Implements Ownership, Pausable emergency state, and Reentrancy protection.
 */
contract VeriPhysLedger is Ownable, Pausable, ReentrancyGuard {
    
    struct ContentRecord {
        address creator;     // Original author's wallet address
        uint256 timestamp;   // Block timestamp of registration
        uint256 blockNumber; // Blockchain height at the time of anchoring
    }

    // State Mapping: Content Hash => Technical Record
    mapping(bytes32 => ContentRecord) private _ledger;

    // Events for Off-chain Monitoring (Subgraphs/Frontend)
    event ContentAnchored(bytes32 indexed hash, address indexed creator, uint256 timestamp);
    event EmergencyStop(address indexed admin, bool status);

    /**
     * @dev Sets the deployer as the initial owner.
     */
    constructor() Ownable(msg.sender) {}

    /**
     * @notice Anchor a digital fingerprint to the immutable ledger.
     * @param _contentHash The 32-byte hash generated by the VeriPhys Rust engine.
     * @dev Protected by nonReentrant and whenNotPaused modifiers.
     */
    function anchorContent(bytes32 _contentHash) external whenNotPaused nonReentrant {
        require(_contentHash != bytes32(0), "VeriPhys: Hash cannot be empty");
        require(_ledger[_contentHash].timestamp == 0, "VeriPhys: Hash already anchored");

        _ledger[_contentHash] = ContentRecord({
            creator: msg.sender,
            timestamp: block.timestamp,
            blockNumber: block.number
        });

        emit ContentAnchored(_contentHash, msg.sender, block.timestamp);
    }

    /**
     * @notice Verify the authenticity and history of a content hash.
     * @param _contentHash The hash to look up.
     * @return creator The address of the original author.
     * @return timestamp The Unix timestamp of registration.
     * @return blockNumber The block number of the transaction.
     * @return exists Boolean indicating if the record is valid.
     */
    function verifyContent(bytes32 _contentHash) external view returns (
        address creator, 
        uint256 timestamp, 
        uint256 blockNumber,
        bool exists
    ) {
        ContentRecord memory record = _ledger[_contentHash];
        return (record.creator, record.timestamp, record.blockNumber, record.timestamp != 0);
    }

    // --- Admin & Governance Functions ---

    /**
     * @notice Emergency stop to protect user data in case of detected vulnerabilities.
     * @onlyOwner Restricted to the protocol administrator.
     */
    function pause() external onlyOwner {
        _pause();
        emit EmergencyStop(msg.sender, true);
    }

    /**
     * @notice Resumes protocol operations.
     */
    function unpause() external onlyOwner {
        _unpause();
        emit EmergencyStop(msg.sender, false);
    }
}
