// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title VeriPhysIntegrityLedger
 * @dev High-performance anchoring for digital asset fingerprints.
 * Optimized for gas efficiency and seamless integration with Rust-based backends.
 */
contract IntegrityLedger {
    
    // Structure to store asset details on-chain
    struct Anchor {
        uint256 timestamp;
        address author;
        bool exists;
    }

    // Mapping from SHA3-256 hash to Anchor data
    mapping(bytes32 => Anchor) private ledger;

    // --- Custom Errors (Gas Efficient & Rust Friendly) ---
    error ContentAlreadyAnchored(bytes32 contentHash, uint256 timestamp);
    error InvalidHash();

    // --- Events ---
    // Added 'indexed' to timestamp for easier filtering in ethers-rs
    event ContentAnchored(bytes32 indexed contentHash, address indexed author, uint256 indexed timestamp);

    /**
     * @notice Anchors a unique SHA3-256 fingerprint to the blockchain.
     * @param _contentHash The 32-byte hash generated by the VeriPhys Rust Engine.
     */
    function anchorContent(bytes32 _contentHash) external {
        // 1. Validation: Ensure hash is not empty
        if (_contentHash == bytes32(0)) revert InvalidHash();

        // 2. State Check: Prevent re-anchoring to save gas
        if (ledger[_contentHash].exists) {
            revert ContentAlreadyAnchored(_contentHash, ledger[_contentHash].timestamp);
        }

        // 3. Update State
        ledger[_contentHash] = Anchor({
            timestamp: block.timestamp,
            author: msg.sender,
            exists: true
        });

        // 4. Emit Event
        emit ContentAnchored(_contentHash, msg.sender, block.timestamp);
    }

    /**
     * @notice Verifies if a content hash exists in the global ledger.
     * @param _contentHash The SHA3-256 hash to check.
     */
    function verifyContent(bytes32 _contentHash) external view returns (
        bool exists, 
        uint256 timestamp, 
        address author
    ) {
        Anchor storage record = ledger[_contentHash]; // Use storage for direct access
        return (record.exists, record.timestamp, record.author);
    }

    /**
     * @notice Quick check function for backend validation.
     */
    function isAnchored(bytes32 _contentHash) external view returns (bool) {
        return ledger[_contentHash].exists;
    }
}
